INTERNAL - Add commerce as product dependency
adobe/commerce-integration-starter-kit pull request #9
Opened 2024-06-14 18:31 UTC by rojoangel

## Description

Add commerce as a product dependency

## Related Issue

N/A

## Motivation and Context

This marks starter kit projects as dependent on Commerce

## How Has This Been Tested?

N/A
## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2024-06-14 18:42 UTC, pru55e11 reviewed
Do you need to require any specific commerce version? This will be displayed int he agreement that the customer accepts during aquisition

2024-06-14 18:45 UTC, rojoangel commented
As far as I am concerned, no specific version is needed, but let me double-check internally to play on the safe side.

2024-06-14 18:55 UTC, rojoangel commented
On second thought, since the kit relies on the `Adobe I/O Events for Adobe Commerce` which requires Adobe Commerce 2.4.4 or higher, I think it may make sense to set this min version.

2024-06-14 19:11 UTC, pru55e11 approved these changes
LGTM!

2024-06-14 23:11 UTC, pru55e11 requested changes
actually, I think COMMC will be the code needed.

2024-06-17 07:41 UTC, nejo approved these changes

2024-06-17 07:46 UTC, pablomoreno61 approved these changes

2024-06-17 07:46 UTC, pablomoreno61 commented on app.config.yaml
> +productDependencies:
Didn't know about this! I just found a wiki mentioning something about it. Do you have more info about possible codes and the impact of this addition in an app builder project?

2024-06-17 15:59 UTC, pru55e11 commented on app.config.yaml
> +productDependencies:
We're working internally on creating a list of product codes in our docs.

2024-06-19 07:41 UTC, merged